#############################################################################
# Makefile for building: CenterPlay
# Generated by qmake (3.1) (Qt 5.9.0)
# Project:  CenterPlay.pro
# Template: app
# Command: /home/cesar/Qt5.9.0/5.9/gcc_64/bin/qmake -o Makefile CenterPlay.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_QML_DEBUG -DQT_WEBENGINE_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB -DQT_WEBVIEW_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/home/cesar/Qt5.9.0/5.9/gcc_64/include -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWebEngine -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWebEngineCore -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtQuick -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtSvg -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWidgets -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtGui -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWebChannel -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtQml -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtNetwork -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtPositioning -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWebView -I. -isystem /usr/include/libdrm -I/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/linux-g++
QMAKE         = /home/cesar/Qt5.9.0/5.9/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL_FILE = /home/cesar/Qt5.9.0/5.9/gcc_64/bin/qmake -install qinstall file
QINSTALL_PROGRAM = /home/cesar/Qt5.9.0/5.9/gcc_64/bin/qmake -install qinstall program
QINSTALL_DIR  = /home/cesar/Qt5.9.0/5.9/gcc_64/bin/qmake -install qinstall directory
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = CenterPlay1.0.0
DISTDIR = /home/cesar/Documentos/UFAL/OITAVO/TSO/CenterPlay_Merged/CenterPlay/.tmp/CenterPlay1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/cesar/Qt5.9.0/5.9/gcc_64/lib -Wl,-rpath-link,/home/cesar/Qt5.9.0/5.9/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/cesar/Qt5.9.0/5.9/gcc_64/lib -lQt5WebEngine -lQt5WebEngineCore -lQt5Quick -lQt5Svg -lQt5Widgets -lQt5Gui -lQt5WebChannel -lQt5Qml -lQt5Network -lQt5Positioning -lQt5Core -lQt5WebView -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		scriptlauncher.cpp \
		tetrixlauncher.cpp qrc_qml.cpp \
		moc_scriptlauncher.cpp \
		moc_tetrixlauncher.cpp
OBJECTS       = main.o \
		scriptlauncher.o \
		tetrixlauncher.o \
		qrc_qml.o \
		moc_scriptlauncher.o \
		moc_tetrixlauncher.o
DIST          = /home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/spec_pre.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/common/unix.conf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/common/linux.conf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/common/sanitize.conf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/common/gcc-base.conf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/common/g++-base.conf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/common/g++-unix.conf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/qconfig.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/qt_functions.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/qt_config.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/spec_post.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/toolchain.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/default_pre.prf \
		deployment.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/resolve_config.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/default_post.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/qml_debug.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/warn_on.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/qt.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/resources.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/moc.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/uic.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/unix/thread.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/qmake_use.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/file_copies.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/exceptions.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/yacc.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/lex.prf \
		CenterPlay.pro scriptlauncher.h \
		tetrixlauncher.h main.cpp \
		scriptlauncher.cpp \
		tetrixlauncher.cpp
QMAKE_TARGET  = CenterPlay
DESTDIR       = 
TARGET        = CenterPlay


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CenterPlay.pro /home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/linux-g++/qmake.conf /home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/spec_pre.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/common/unix.conf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/common/linux.conf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/common/sanitize.conf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/common/gcc-base.conf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/common/g++-base.conf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/common/g++-unix.conf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/qconfig.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/qt_functions.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/qt_config.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/spec_post.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/toolchain.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/default_pre.prf \
		deployment.pri \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/resolve_config.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/default_post.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/qml_debug.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/warn_on.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/qt.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/resources.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/moc.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/uic.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/unix/thread.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/qmake_use.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/file_copies.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/exceptions.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/yacc.prf \
		/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/lex.prf \
		CenterPlay.pro \
		qml.qrc \
		/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5WebEngine.prl \
		/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5WebEngineCore.prl \
		/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5Quick.prl \
		/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5Svg.prl \
		/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5Widgets.prl \
		/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5Gui.prl \
		/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5WebChannel.prl \
		/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5Qml.prl \
		/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5Network.prl \
		/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5Positioning.prl \
		/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5Core.prl \
		/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5WebView.prl
	$(QMAKE) -o Makefile CenterPlay.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/spec_pre.prf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/common/unix.conf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/common/linux.conf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/common/sanitize.conf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/common/gcc-base.conf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/common/g++-base.conf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/common/g++-unix.conf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/qconfig.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_charts.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_script.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webview.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/qt_functions.prf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/qt_config.prf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/spec_post.prf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/toolchain.prf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/default_pre.prf:
deployment.pri:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/resolve_config.prf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/default_post.prf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/qml_debug.prf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/warn_on.prf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/qt.prf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/resources.prf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/moc.prf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/unix/opengl.prf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/uic.prf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/unix/thread.prf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/qmake_use.prf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/file_copies.prf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/testcase_targets.prf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/exceptions.prf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/yacc.prf:
/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/lex.prf:
CenterPlay.pro:
qml.qrc:
/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5WebEngine.prl:
/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5WebEngineCore.prl:
/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5Quick.prl:
/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5Svg.prl:
/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5Widgets.prl:
/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5Gui.prl:
/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5WebChannel.prl:
/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5Qml.prl:
/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5Network.prl:
/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5Positioning.prl:
/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5Core.prl:
/home/cesar/Qt5.9.0/5.9/gcc_64/lib/libQt5WebView.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile CenterPlay.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents scriptlauncher.h tetrixlauncher.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp scriptlauncher.cpp tetrixlauncher.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		/home/cesar/Qt5.9.0/5.9/gcc_64/bin/rcc \
		FolderVideo.qml \
		PagePicture.qml \
		Picture.qml \
		PageVideo.qml \
		PageMainForm.ui.qml \
		PageYoutube.qml \
		PageMain.qml \
		FolderMusic.qml \
		PageMusic.qml \
		PagePictureForm.ui.qml \
		PageGameForm.ui.qml \
		PageGame.qml \
		PageSpotify.qml \
		PageVideoForm.ui.qml \
		main.qml \
		Player.qml \
		PageNetflix.qml \
		FolderPicture.qml \
		PageDeezer.qml \
		PageMusicForm.ui.qml \
		img/game_icon.png \
		img/spotify.png \
		img/youtube.ico \
		img/power_icon.png \
		img/usb_red.png \
		img/usb_indigo.png \
		img/video_icon.png \
		img/usb_orange.png \
		img/netflix.png \
		img/deezer.png \
		img/usb_green.png \
		img/tetris.png \
		img/music_icon.png \
		img/image_icon.png
	/home/cesar/Qt5.9.0/5.9/gcc_64/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_scriptlauncher.cpp moc_tetrixlauncher.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_scriptlauncher.cpp moc_tetrixlauncher.cpp
moc_scriptlauncher.cpp: /home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/QObject \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qobject.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qobjectdefs.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qnamespace.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qglobal.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qconfig.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qtcore-config.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qsystemdetection.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qprocessordetection.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qtypeinfo.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qsysinfo.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qlogging.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qflags.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qbasicatomic.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qgenericatomic.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qglobalstatic.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qmutex.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qnumeric.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qversiontagging.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qstring.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qchar.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearray.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qrefcount.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qarraydata.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringbuilder.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qlist.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qalgorithms.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qiterator.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qhashfunctions.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qpair.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearraylist.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringlist.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qregexp.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringmatcher.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qcoreevent.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qscopedpointer.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qmetatype.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qobject_impl.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/QProcess \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qprocess.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qiodevice.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qshareddata.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qhash.h \
		scriptlauncher.h \
		moc_predefs.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/bin/moc
	/home/cesar/Qt5.9.0/5.9/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/linux-g++ -I/home/cesar/Documentos/UFAL/OITAVO/TSO/CenterPlay_Merged/CenterPlay -I/home/cesar/Qt5.9.0/5.9/gcc_64/include -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWebEngine -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWebEngineCore -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtQuick -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtSvg -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWidgets -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtGui -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWebChannel -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtQml -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtNetwork -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtPositioning -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWebView -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include scriptlauncher.h -o moc_scriptlauncher.cpp

moc_tetrixlauncher.cpp: /home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/QObject \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qobject.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qobjectdefs.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qnamespace.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qglobal.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qconfig.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qtcore-config.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qsystemdetection.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qprocessordetection.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qtypeinfo.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qsysinfo.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qlogging.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qflags.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qbasicatomic.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qgenericatomic.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qglobalstatic.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qmutex.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qnumeric.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qversiontagging.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qstring.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qchar.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearray.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qrefcount.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qarraydata.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringbuilder.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qlist.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qalgorithms.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qiterator.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qhashfunctions.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qpair.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearraylist.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringlist.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qregexp.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringmatcher.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qcoreevent.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qscopedpointer.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qmetatype.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qobject_impl.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/QProcess \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qprocess.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qiodevice.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qshareddata.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qhash.h \
		tetrixlauncher.h \
		moc_predefs.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/bin/moc
	/home/cesar/Qt5.9.0/5.9/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/cesar/Qt5.9.0/5.9/gcc_64/mkspecs/linux-g++ -I/home/cesar/Documentos/UFAL/OITAVO/TSO/CenterPlay_Merged/CenterPlay -I/home/cesar/Qt5.9.0/5.9/gcc_64/include -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWebEngine -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWebEngineCore -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtQuick -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtSvg -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWidgets -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtGui -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWebChannel -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtQml -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtNetwork -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtPositioning -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore -I/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWebView -I/usr/include/c++/5 -I/usr/include/x86_64-linux-gnu/c++/5 -I/usr/include/c++/5/backward -I/usr/lib/gcc/x86_64-linux-gnu/5/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/5/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include tetrixlauncher.h -o moc_tetrixlauncher.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp /home/cesar/Qt5.9.0/5.9/gcc_64/include/QtGui/QGuiApplication \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtGui/qguiapplication.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtGui/qtguiglobal.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qglobal.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qconfig.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qtcore-config.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qsystemdetection.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qprocessordetection.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qtypeinfo.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qsysinfo.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qlogging.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qflags.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qbasicatomic.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qgenericatomic.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qglobalstatic.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qmutex.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qnumeric.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qversiontagging.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtGui/qtgui-config.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qcoreapplication.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qstring.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qchar.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearray.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qrefcount.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qnamespace.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qarraydata.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringbuilder.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qobject.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qobjectdefs.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qlist.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qalgorithms.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qiterator.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qhashfunctions.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qpair.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearraylist.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringlist.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qregexp.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringmatcher.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qcoreevent.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qscopedpointer.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qmetatype.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qobject_impl.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qeventloop.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtGui/qwindowdefs.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtGui/qwindowdefs_win.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtGui/qinputmethod.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qlocale.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qvariant.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qmap.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qdebug.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qhash.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qtextstream.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qiodevice.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qvector.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qpoint.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qset.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qcontiguouscache.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qsharedpointer.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qshareddata.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qsharedpointer_impl.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qsize.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtQml/QQmlApplicationEngine \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtQml/qqmlapplicationengine.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtQml/qqmlengine.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qurl.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qurlquery.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtQml/qjsengine.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtQml/qjsvalue.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtQml/qtqmlglobal.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtQml/qtqml-config.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtNetwork/qtnetworkglobal.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtNetwork/qtnetwork-config.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtQml/qqml.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtQml/qqmlprivate.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtQml/qqmlparserstatus.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtQml/qqmlpropertyvaluesource.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtQml/qqmllist.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qmetaobject.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtQml/qqmlerror.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtQml/qqmldebug.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtQml/QQmlContext \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtQml/qqmlcontext.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/QUrl \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWebView/QtWebView \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWebView/QtWebViewDepends \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWebView/qtwebviewfunctions.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWebView/qwebview_global.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWebView/qtwebviewversion.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWebEngine/qtwebengineglobal.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWebEngineCore/QWebEngineCookieStore \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWebEngineCore/qwebenginecookiestore.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWebEngineCore/qtwebenginecoreglobal.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtWebEngineCore/qwebenginecallback.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtNetwork/qnetworkcookie.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/QSharedDataPointer \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/QList \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/QMetaType \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/QObject \
		scriptlauncher.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/QProcess \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qprocess.h \
		tetrixlauncher.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

scriptlauncher.o: scriptlauncher.cpp scriptlauncher.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/QObject \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qobject.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qobjectdefs.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qnamespace.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qglobal.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qconfig.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qtcore-config.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qsystemdetection.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qprocessordetection.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qtypeinfo.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qsysinfo.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qlogging.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qflags.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qbasicatomic.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qgenericatomic.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qglobalstatic.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qmutex.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qnumeric.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qversiontagging.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qstring.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qchar.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearray.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qrefcount.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qarraydata.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringbuilder.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qlist.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qalgorithms.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qiterator.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qhashfunctions.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qpair.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearraylist.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringlist.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qregexp.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringmatcher.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qcoreevent.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qscopedpointer.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qmetatype.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qobject_impl.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/QProcess \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qprocess.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qiodevice.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qshareddata.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qhash.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scriptlauncher.o scriptlauncher.cpp

tetrixlauncher.o: tetrixlauncher.cpp tetrixlauncher.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/QObject \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qobject.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qobjectdefs.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qnamespace.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qglobal.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qconfig.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qtcore-config.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qsystemdetection.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qprocessordetection.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qcompilerdetection.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qtypeinfo.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qsysinfo.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qlogging.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qflags.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qbasicatomic.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_bootstrap.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qgenericatomic.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_cxx11.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qatomic_msvc.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qglobalstatic.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qmutex.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qnumeric.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qversiontagging.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qobjectdefs_impl.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qstring.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qchar.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearray.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qrefcount.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qarraydata.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringbuilder.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qlist.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qalgorithms.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qiterator.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qhashfunctions.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qpair.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qbytearraylist.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringlist.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qregexp.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qstringmatcher.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qcoreevent.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qscopedpointer.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qmetatype.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qvarlengtharray.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qcontainerfwd.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qobject_impl.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/QProcess \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qprocess.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qiodevice.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qshareddata.h \
		/home/cesar/Qt5.9.0/5.9/gcc_64/include/QtCore/qhash.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tetrixlauncher.o tetrixlauncher.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_scriptlauncher.o: moc_scriptlauncher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scriptlauncher.o moc_scriptlauncher.cpp

moc_tetrixlauncher.o: moc_tetrixlauncher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tetrixlauncher.o moc_tetrixlauncher.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/CenterPlay/bin || mkdir -p $(INSTALL_ROOT)/opt/CenterPlay/bin
	-$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/CenterPlay/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/CenterPlay/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/CenterPlay/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

